services:
  rabbitmq-container:
    image: rabbitmq:3.11-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - internal

  ping:
    container_name: pong
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq-container
    networks:
      - internal
    environment:
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672

networks:
  internal:
    name: internal